[package]
name = "xt-oss"
version = "0.1.0"
edition = "2021"
rust-version = "1.73"
authors = ["isme.sun <isme.sun@icloud.com>"]
description = "Aliyun OSS SDK"
license = "MIT OR Apache-2.0"
homepage = "https://www.xuetube.com/res/xuetiube-oss"
keywords = ["oss", "aliyun"]
categories = ["filesystem"]
# publish = false
default-run = "xt-oss"

[badges]
maintenance = { status = "actively-developed" }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.5"
chrono = "0.4.31"
dotenv = "0.15.0"
urlencoding = "2.1.3"
hmac-sha1 = "0.2.1"
rust-crypto = "0.2.36"
serde-xml-rs = "0.6.0"
serde_json = "1.0.108"
serde_qs = "0.12.0"
tokio = { version = "1.34.0", features = ["rt-multi-thread", "macros"] }
reqwest = { version = "0.11.22"}
serde = { version = "1.0.192", features = ["serde_derive"] }